name: 'Get Git Log Action'
description: 'Get git log from specify git tag to the present'
author: 'Mason'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  type:
    description: 'Log filter type'
    required: false
  value:
    description: 'Specify git value'
    required: false
  value:
    description: 'Log path'
    required: false
outputs:
  log:
    description: 'git logs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.type }}
    - ${{ inputs.value }}
    - ${{ inputs.path }}